### ISSUE TITLE
SWidget Integration Broken in HA

### ISSUE THREAD

**Issue by visbits** [michaelkkehoe/haswidget2#4]
2024-11-11 23:30:35.703 ERROR (MainThread) [custom_components.swidget] Setup Data: {'device': 'REDACTED', 'host': 'REDACTED', 'password': 'REDACTED'}
2024-11-11 23:30:36.474 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Swidget Device for swidget
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/swidget/__init__.py", line 84, in async_setup_entry
    device: SwidgetDevice = await discover_single(entry.data['host'],
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/swidget/swidgetclient/discovery.py", line 73, in discover_single
    await swidget_device.get_summary()
  File "/config/custom_components/swidget/swidgetclient/device.py", line 63, in get_summary
    await self.process_summary(summary)
  File "/config/custom_components/swidget/swidgetclient/device.py", line 67, in process_summary
    self.model = summary["model"]
                 ~~~~~~~^^^^^^^^^
KeyError: 'model'

**Comment by michaelkkehoe** [comment]
Hi,

Could you please provide some specifics. What kind of insert, what firmware is it on? 

Have you also provisioned the device with a password?

**Comment by michaelkkehoe** [comment]
Closing due to staleness
